#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source $OPENSHIFT_CARTRIDGE_SDK_BASH

set -e

echo 1>&2
echo "Updating composer" 1>&2
if [ ! -f "$OPENSHIFT_DATA_DIR/composer.phar" ]; then
    curl -s https://getcomposer.org/installer | php -- --install-dir=$OPENSHIFT_DATA_DIR
else
    php $OPENSHIFT_DATA_DIR/composer.phar self-update
fi
cd $OPENSHIFT_REPO_DIR && php $OPENSHIFT_DATA_DIR/composer.phar install --no-dev

echo 1>&2
echo "Migrating storage and log directories..." 1>&2
echo 1>&2
# If this is initial installation, copy the default storage directory
# from official Laravel installation and remove the log directory
#
#if [ ! -d ${OPENSHIFT_DATA_DIR}storage ]; then
#  mv ${OPENSHIFT_REPO_DIR}storage ${OPENSHIFT_DATA_DIR}storage
#  rm -rf ${OPENSHIFT_DATA_DIR}storage/logs
#fi

# Create symlink to new storage directory location
#ln -sf ${OPENSHIFT_DATA_DIR}storage   ${OPENSHIFT_REPO_DIR}storage

# Create a symlink to the new log directory location
#ln -sf ${OPENSHIFT_LOG_DIR}   ${OPENSHIFT_DATA_DIR}storage/logs
unlink ${OPENSHIFT_LOG_DIR}
mkdir ${OPENSHIFT_LOG_DIR}
echo ${OPENSHIFT_DATA_DIR}
echo ${OPENSHIFT_REPO_DIR}



echo 1>&2
echo "Running 'php artisan migrate --force'..." 1>&2
echo 1>&2
pushd ${OPENSHIFT_REPO_DIR} > /dev/null
#php artisan migrate --force
popd > /dev/null