language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm


before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add .travis.php.ini; fi;'
  - composer self-update
  - composer install --no-interaction

script: vendor/bin/phpunit

matrix:
  allow_failures:
    - php: 5.4
    - php: hhvm
  fast_finish: true