language: php
sudo: true
php:
  - 5.4
before_script:
  - node -v
  - npm -v
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
  - sudo apt-get update;
  - sudo apt-get install gcc-4.8 g++-4.8;
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20;
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20;
  - sudo g++ --version;
  - sudo apt-get update -qq;
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add .travis.php.ini; fi;'
  - composer self-update
  - composer install --no-interaction
  - npm install
  - bower install

script: vendor/bin/phpunit

matrix:
  allow_failures:
  - php: 5.4
  - php: 7.0
  fast_finish: true

cache:
  directories:
    - node_modules
    - vendor

after_success:
   - node_modules/.bin/gulp
   - git config user.name "travis"
   - git config user.email "urakozz@travis.com"
   - git add -A
   - git commit -m "travis build"

deploy:
  provider: openshift
  user: urakozz@me.com
  password:
    secure: KnZqyaTVrpWR6BgvEq9wgknkOpBn1W2S6XorHmaS5MLjeBdp12nC+gJTBNY1VmuXwQBfiwpfYQ9pqp0EqC2gLY6k8lkpWLpbklRM8ZVA/sKznD0563H0LCnAbpw181KSgDfeh/n8+uwobjuSpIipjXG6MFIYmzLzUQA0GeqryY4=
  app: php
  domain: kozz
  on:
    repo: urakozz/visa-status
  skip_cleanup: true
