language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

services:
  - redis-server

before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add .travis.php.ini; fi;'
  - composer self-update
  - composer install --no-interaction

script: vendor/bin/phpunit --debug --coverage-clover build/logs/clover.xml

after_success:
    - vendor/bin/test-reporter

matrix:
  allow_failures:
    - php: 5.4
    - php: hhvm
  fast_finish: true