language: php
sudo: false
php:
  - 5.4
before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add .travis.php.ini; fi;'
  - composer self-update
  - composer install --no-interaction
script: vendor/bin/phpunit
matrix:
  allow_failures:
  - php: 5.4
  - php: 7.0
  fast_finish: true

after_success:
   - npm install
   - bower install
   - node_modules/.bin/gulp
   - git config user.name "travis"
   - git config user.email "urakozz@travis.com"
   - git add -A
   - git commit -m "travis build"

deploy:
  provider: openshift
  user: urakozz@me.com
  password:
    secure: KnZqyaTVrpWR6BgvEq9wgknkOpBn1W2S6XorHmaS5MLjeBdp12nC+gJTBNY1VmuXwQBfiwpfYQ9pqp0EqC2gLY6k8lkpWLpbklRM8ZVA/sKznD0563H0LCnAbpw181KSgDfeh/n8+uwobjuSpIipjXG6MFIYmzLzUQA0GeqryY4=
  app: php
  domain: kozz
  on:
    repo: urakozz/visa-status
  skip_cleanup: true
